// Mocks generated by Mockito 5.4.6 from annotations
// in carp_study_app/test/heart_rate_data_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:carp_core/carp_core.dart' as _i3;
import 'package:carp_mobile_sensing/carp_mobile_sensing.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:permission_handler/permission_handler.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSmartphoneStudy_0 extends _i1.SmartFake
    implements _i2.SmartphoneStudy {
  _FakeSmartphoneStudy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSmartphoneDeploymentExecutor_1 extends _i1.SmartFake
    implements _i2.SmartphoneDeploymentExecutor {
  _FakeSmartphoneDeploymentExecutor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [SmartphoneStudyController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartphoneStudyController extends _i1.Mock
    implements _i2.SmartphoneStudyController {
  @override
  _i2.SmartphoneStudy get study =>
      (super.noSuchMethod(
            Invocation.getter(#study),
            returnValue: _FakeSmartphoneStudy_0(
              this,
              Invocation.getter(#study),
            ),
            returnValueForMissingStub: _FakeSmartphoneStudy_0(
              this,
              Invocation.getter(#study),
            ),
          )
          as _i2.SmartphoneStudy);

  @override
  List<_i3.DeviceConfiguration<_i3.DeviceRegistration>>
  get remainingDevicesToRegister =>
      (super.noSuchMethod(
            Invocation.getter(#remainingDevicesToRegister),
            returnValue: <_i3.DeviceConfiguration<_i3.DeviceRegistration>>[],
            returnValueForMissingStub:
                <_i3.DeviceConfiguration<_i3.DeviceRegistration>>[],
          )
          as List<_i3.DeviceConfiguration<_i3.DeviceRegistration>>);

  @override
  Map<_i4.Permission, _i4.PermissionStatus> get permissions =>
      (super.noSuchMethod(
            Invocation.getter(#permissions),
            returnValue: <_i4.Permission, _i4.PermissionStatus>{},
            returnValueForMissingStub: <_i4.Permission, _i4.PermissionStatus>{},
          )
          as Map<_i4.Permission, _i4.PermissionStatus>);

  @override
  _i2.SmartphoneDeploymentExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeSmartphoneDeploymentExecutor_1(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeSmartphoneDeploymentExecutor_1(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.SmartphoneDeploymentExecutor);

  @override
  String get privacySchemaName =>
      (super.noSuchMethod(
            Invocation.getter(#privacySchemaName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#privacySchemaName),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#privacySchemaName),
            ),
          )
          as String);

  @override
  _i6.Stream<_i3.Measurement> get measurements =>
      (super.noSuchMethod(
            Invocation.getter(#measurements),
            returnValue: _i6.Stream<_i3.Measurement>.empty(),
            returnValueForMissingStub: _i6.Stream<_i3.Measurement>.empty(),
          )
          as _i6.Stream<_i3.Measurement>);

  @override
  _i6.Stream<_i3.Measurement> measurementsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#measurementsByType, [type]),
            returnValue: _i6.Stream<_i3.Measurement>.empty(),
            returnValueForMissingStub: _i6.Stream<_i3.Measurement>.empty(),
          )
          as _i6.Stream<_i3.Measurement>);

  @override
  _i6.Future<void> tryRegisterConnectedDevice(
    _i3.DeviceConfiguration<_i3.DeviceRegistration>? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryRegisterConnectedDevice, [device]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> tryRegisterRemainingDevicesToRegister() =>
      (super.noSuchMethod(
            Invocation.method(#tryRegisterRemainingDevicesToRegister, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> tryUnregisterDisconnectedDevice(
    _i3.DeviceConfiguration<_i3.DeviceRegistration>? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryUnregisterDisconnectedDevice, [device]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> tryReregisterDevice(
    _i3.DeviceConfiguration<_i3.DeviceRegistration>? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tryReregisterDevice, [device]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> askForAllPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#askForAllPermissions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void restart() => super.noSuchMethod(
    Invocation.method(#restart, []),
    returnValueForMissingStub: null,
  );

  @override
  void resume() => super.noSuchMethod(
    Invocation.method(#resume, []),
    returnValueForMissingStub: null,
  );

  @override
  void pause() => super.noSuchMethod(
    Invocation.method(#pause, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
