// Mocks generated by Mockito 5.4.6 from annotations
// in carp_study_app/test/services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:carp_core/carp_core.dart' as _i5;
import 'package:carp_mobile_sensing/carp_mobile_sensing.dart' as _i6;
import 'package:carp_study_app/main.dart' as _i4;
import 'package:carp_webservices/carp_auth/carp_auth.dart' as _i3;
import 'package:carp_webservices/carp_services/carp_services.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:research_package/research_package.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeCarpApp_1 extends _i1.SmartFake implements _i2.CarpApp {
  _FakeCarpApp_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeCarpAuthProperties_2 extends _i1.SmartFake implements _i3.CarpAuthProperties {
  _FakeCarpAuthProperties_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeCarpUser_3 extends _i1.SmartFake implements _i3.CarpUser {
  _FakeCarpUser_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [CarpBackend].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarpBackend extends _i1.Mock implements _i4.CarpBackend {
  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_0(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_0(this, Invocation.getter(#uri)),
          )
          as Uri);

  @override
  Uri get authUri =>
      (super.noSuchMethod(
            Invocation.getter(#authUri),
            returnValue: _FakeUri_0(this, Invocation.getter(#authUri)),
            returnValueForMissingStub: _FakeUri_0(this, Invocation.getter(#authUri)),
          )
          as Uri);

  @override
  _i2.CarpApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeCarpApp_1(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeCarpApp_1(this, Invocation.getter(#app)),
          )
          as _i2.CarpApp);

  @override
  _i3.CarpAuthProperties get authProperties =>
      (super.noSuchMethod(
            Invocation.getter(#authProperties),
            returnValue: _FakeCarpAuthProperties_2(this, Invocation.getter(#authProperties)),
            returnValueForMissingStub: _FakeCarpAuthProperties_2(this, Invocation.getter(#authProperties)),
          )
          as _i3.CarpAuthProperties);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(Invocation.getter(#isAuthenticated), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  List<_i5.ActiveParticipationInvitation> get invitations =>
      (super.noSuchMethod(
            Invocation.getter(#invitations),
            returnValue: <_i5.ActiveParticipationInvitation>[],
            returnValueForMissingStub: <_i5.ActiveParticipationInvitation>[],
          )
          as List<_i5.ActiveParticipationInvitation>);

  @override
  set user(_i3.CarpUser? user) => super.noSuchMethod(Invocation.setter(#user, user), returnValueForMissingStub: null);

  @override
  set invitations(List<_i5.ActiveParticipationInvitation>? value) =>
      super.noSuchMethod(Invocation.setter(#invitations, value), returnValueForMissingStub: null);

  @override
  set study(_i6.SmartphoneStudy? study) =>
      super.noSuchMethod(Invocation.setter(#study, study), returnValueForMissingStub: null);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> authenticateWithMagicLink(String? uri) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithMagicLink, [uri]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.CarpUser> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i7.Future<_i3.CarpUser>.value(_FakeCarpUser_3(this, Invocation.method(#refresh, []))),
            returnValueForMissingStub: _i7.Future<_i3.CarpUser>.value(
              _FakeCarpUser_3(this, Invocation.method(#refresh, [])),
            ),
          )
          as _i7.Future<_i3.CarpUser>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.ActiveParticipationInvitation>> getInvitations() =>
      (super.noSuchMethod(
            Invocation.method(#getInvitations, []),
            returnValue: _i7.Future<List<_i5.ActiveParticipationInvitation>>.value(
              <_i5.ActiveParticipationInvitation>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i5.ActiveParticipationInvitation>>.value(
              <_i5.ActiveParticipationInvitation>[],
            ),
          )
          as _i7.Future<List<_i5.ActiveParticipationInvitation>>);

  @override
  _i7.Future<_i5.InformedConsentInput?> uploadInformedConsent(_i8.RPTaskResult? consent) =>
      (super.noSuchMethod(
            Invocation.method(#uploadInformedConsent, [consent]),
            returnValue: _i7.Future<_i5.InformedConsentInput?>.value(),
            returnValueForMissingStub: _i7.Future<_i5.InformedConsentInput?>.value(),
          )
          as _i7.Future<_i5.InformedConsentInput?>);

  @override
  _i7.Future<_i5.InformedConsentInput?>? getInformedConsentByRole(String? studyDeploymentId, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#getInformedConsentByRole, [studyDeploymentId, role]),
            returnValueForMissingStub: null,
          )
          as _i7.Future<_i5.InformedConsentInput?>?);
}
