// Mocks generated by Mockito 5.4.6 from annotations
// in carp_study_app/test/services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:carp_core/carp_core.dart' as _i3;
import 'package:carp_mobile_sensing/carp_mobile_sensing.dart' as _i2;
import 'package:carp_study_app/main.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:research_package/research_package.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAppTask_1 extends _i1.SmartFake implements _i2.AppTask {
  _FakeAppTask_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAppTaskExecutor_3<TConfig extends _i2.AppTask> extends _i1.SmartFake
    implements _i2.AppTaskExecutor<TConfig> {
  _FakeAppTaskExecutor_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBackgroundTaskExecutor_4 extends _i1.SmartFake implements _i2.BackgroundTaskExecutor {
  _FakeBackgroundTaskExecutor_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDeploymentService_5 extends _i1.SmartFake implements _i3.DeploymentService {
  _FakeDeploymentService_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [Backend].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackend extends _i1.Mock implements _i4.Backend {
  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_0(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_0(this, Invocation.getter(#uri)),
          )
          as Uri);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(Invocation.getter(#isAuthenticated), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  set study(_i2.SmartphoneStudy? study) =>
      super.noSuchMethod(Invocation.setter(#study, study), returnValueForMissingStub: null);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> magicLinkForCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#magicLinkForCode, [code]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> authenticateWithMagicLink(String? uri) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithMagicLink, [uri]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ActiveParticipationInvitation>> getInvitations() =>
      (super.noSuchMethod(
            Invocation.method(#getInvitations, []),
            returnValue: _i5.Future<List<_i3.ActiveParticipationInvitation>>.value(
              <_i3.ActiveParticipationInvitation>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i3.ActiveParticipationInvitation>>.value(
              <_i3.ActiveParticipationInvitation>[],
            ),
          )
          as _i5.Future<List<_i3.ActiveParticipationInvitation>>);

  @override
  _i5.Future<_i3.InformedConsentInput?> uploadInformedConsent(_i6.RPTaskResult? consent) =>
      (super.noSuchMethod(
            Invocation.method(#uploadInformedConsent, [consent]),
            returnValue: _i5.Future<_i3.InformedConsentInput?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.InformedConsentInput?>.value(),
          )
          as _i5.Future<_i3.InformedConsentInput?>);

  @override
  _i5.Future<_i3.InformedConsentInput?> getInformedConsentByRole(String? studyDeploymentId, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#getInformedConsentByRole, [studyDeploymentId, role]),
            returnValue: _i5.Future<_i3.InformedConsentInput?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.InformedConsentInput?>.value(),
          )
          as _i5.Future<_i3.InformedConsentInput?>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(Invocation.getter(#isAuthenticated), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#username)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#username)),
          )
          as String);

  @override
  String get friendlyUsername =>
      (super.noSuchMethod(
            Invocation.getter(#friendlyUsername),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#friendlyUsername)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#friendlyUsername)),
          )
          as String);

  @override
  Uri get serverUri =>
      (super.noSuchMethod(
            Invocation.getter(#serverUri),
            returnValue: _FakeUri_0(this, Invocation.getter(#serverUri)),
            returnValueForMissingStub: _FakeUri_0(this, Invocation.getter(#serverUri)),
          )
          as Uri);

  @override
  List<_i3.ActiveParticipationInvitation> get invitations =>
      (super.noSuchMethod(
            Invocation.getter(#invitations),
            returnValue: <_i3.ActiveParticipationInvitation>[],
            returnValueForMissingStub: <_i3.ActiveParticipationInvitation>[],
          )
          as List<_i3.ActiveParticipationInvitation>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ActiveParticipationInvitation>> getInvitations() =>
      (super.noSuchMethod(
            Invocation.method(#getInvitations, []),
            returnValue: _i5.Future<List<_i3.ActiveParticipationInvitation>>.value(
              <_i3.ActiveParticipationInvitation>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i3.ActiveParticipationInvitation>>.value(
              <_i3.ActiveParticipationInvitation>[],
            ),
          )
          as _i5.Future<List<_i3.ActiveParticipationInvitation>>);

  @override
  _i5.Future<void> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> authenticateWithMagicLink(String? uri) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithMagicLink, [uri]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> magicLinkForCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#magicLinkForCode, [code]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SystemInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemInfoService extends _i1.Mock implements _i4.SystemInfoService {
  @override
  _i5.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isHealthInstalled() =>
      (super.noSuchMethod(
            Invocation.method(#isHealthInstalled, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool?> getAppHasUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#getAppHasUpdate, []),
            returnValue: _i5.Future<bool?>.value(),
            returnValueForMissingStub: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<void> openAppStore() =>
      (super.noSuchMethod(
            Invocation.method(#openAppStore, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserTask extends _i1.Mock implements _i2.UserTask {
  @override
  _i2.AppTask get task =>
      (super.noSuchMethod(
            Invocation.getter(#task),
            returnValue: _FakeAppTask_1(this, Invocation.getter(#task)),
            returnValueForMissingStub: _FakeAppTask_1(this, Invocation.getter(#task)),
          )
          as _i2.AppTask);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#type)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#type)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#title)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#title)),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#description)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#description)),
          )
          as String);

  @override
  String get instructions =>
      (super.noSuchMethod(
            Invocation.getter(#instructions),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#instructions)),
            returnValueForMissingStub: _i7.dummyValue<String>(this, Invocation.getter(#instructions)),
          )
          as String);

  @override
  bool get notification =>
      (super.noSuchMethod(Invocation.getter(#notification), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  DateTime get triggerTime =>
      (super.noSuchMethod(
            Invocation.getter(#triggerTime),
            returnValue: _FakeDateTime_2(this, Invocation.getter(#triggerTime)),
            returnValueForMissingStub: _FakeDateTime_2(this, Invocation.getter(#triggerTime)),
          )
          as DateTime);

  @override
  DateTime get enqueued =>
      (super.noSuchMethod(
            Invocation.getter(#enqueued),
            returnValue: _FakeDateTime_2(this, Invocation.getter(#enqueued)),
            returnValueForMissingStub: _FakeDateTime_2(this, Invocation.getter(#enqueued)),
          )
          as DateTime);

  @override
  _i2.UserTaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.UserTaskState.initialized,
            returnValueForMissingStub: _i2.UserTaskState.initialized,
          )
          as _i2.UserTaskState);

  @override
  bool get availableForUser =>
      (super.noSuchMethod(Invocation.getter(#availableForUser), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  bool get hasNotificationBeenCreated =>
      (super.noSuchMethod(
            Invocation.getter(#hasNotificationBeenCreated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Stream<_i2.UserTaskState> get stateEvents =>
      (super.noSuchMethod(
            Invocation.getter(#stateEvents),
            returnValue: _i5.Stream<_i2.UserTaskState>.empty(),
            returnValueForMissingStub: _i5.Stream<_i2.UserTaskState>.empty(),
          )
          as _i5.Stream<_i2.UserTaskState>);

  @override
  _i2.AppTaskExecutor<_i2.AppTask> get appTaskExecutor =>
      (super.noSuchMethod(
            Invocation.getter(#appTaskExecutor),
            returnValue: _FakeAppTaskExecutor_3<_i2.AppTask>(this, Invocation.getter(#appTaskExecutor)),
            returnValueForMissingStub: _FakeAppTaskExecutor_3<_i2.AppTask>(this, Invocation.getter(#appTaskExecutor)),
          )
          as _i2.AppTaskExecutor<_i2.AppTask>);

  @override
  _i2.BackgroundTaskExecutor get backgroundTaskExecutor =>
      (super.noSuchMethod(
            Invocation.getter(#backgroundTaskExecutor),
            returnValue: _FakeBackgroundTaskExecutor_4(this, Invocation.getter(#backgroundTaskExecutor)),
            returnValueForMissingStub: _FakeBackgroundTaskExecutor_4(this, Invocation.getter(#backgroundTaskExecutor)),
          )
          as _i2.BackgroundTaskExecutor);

  @override
  bool get hasWidget =>
      (super.noSuchMethod(Invocation.getter(#hasWidget), returnValue: false, returnValueForMissingStub: false) as bool);

  @override
  set id(String? value) => super.noSuchMethod(Invocation.setter(#id, value), returnValueForMissingStub: null);

  @override
  set triggerTime(DateTime? value) =>
      super.noSuchMethod(Invocation.setter(#triggerTime, value), returnValueForMissingStub: null);

  @override
  set enqueued(DateTime? value) =>
      super.noSuchMethod(Invocation.setter(#enqueued, value), returnValueForMissingStub: null);

  @override
  set doneTime(DateTime? value) =>
      super.noSuchMethod(Invocation.setter(#doneTime, value), returnValueForMissingStub: null);

  @override
  set state(_i2.UserTaskState? state) =>
      super.noSuchMethod(Invocation.setter(#state, state), returnValueForMissingStub: null);

  @override
  set hasNotificationBeenCreated(bool? value) =>
      super.noSuchMethod(Invocation.setter(#hasNotificationBeenCreated, value), returnValueForMissingStub: null);

  @override
  set backgroundTaskExecutor(_i2.BackgroundTaskExecutor? value) =>
      super.noSuchMethod(Invocation.setter(#backgroundTaskExecutor, value), returnValueForMissingStub: null);

  @override
  set result(_i3.Data? value) => super.noSuchMethod(Invocation.setter(#result, value), returnValueForMissingStub: null);

  @override
  void onStart() => super.noSuchMethod(Invocation.method(#onStart, []), returnValueForMissingStub: null);

  @override
  void onCancel({bool? dequeue = false}) =>
      super.noSuchMethod(Invocation.method(#onCancel, [], {#dequeue: dequeue}), returnValueForMissingStub: null);

  @override
  void onExpired({bool? dequeue = true}) =>
      super.noSuchMethod(Invocation.method(#onExpired, [], {#dequeue: dequeue}), returnValueForMissingStub: null);

  @override
  void onDone({bool? dequeue = false, _i3.Data? result}) => super.noSuchMethod(
    Invocation.method(#onDone, [], {#dequeue: dequeue, #result: result}),
    returnValueForMissingStub: null,
  );

  @override
  void onNotification() => super.noSuchMethod(Invocation.method(#onNotification, []), returnValueForMissingStub: null);
}

/// A class which mocks [StudyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudyService extends _i1.Mock implements _i4.StudyService {
  @override
  _i3.DeploymentService get deploymentService =>
      (super.noSuchMethod(
            Invocation.getter(#deploymentService),
            returnValue: _FakeDeploymentService_5(this, Invocation.getter(#deploymentService)),
            returnValueForMissingStub: _FakeDeploymentService_5(this, Invocation.getter(#deploymentService)),
          )
          as _i3.DeploymentService);

  @override
  bool get hasStudy =>
      (super.noSuchMethod(Invocation.getter(#hasStudy), returnValue: false, returnValueForMissingStub: false) as bool);

  @override
  bool get isDeployed =>
      (super.noSuchMethod(Invocation.getter(#isDeployed), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  Set<_i3.ExpectedParticipantData?> get expectedParticipantData =>
      (super.noSuchMethod(
            Invocation.getter(#expectedParticipantData),
            returnValue: <_i3.ExpectedParticipantData?>{},
            returnValueForMissingStub: <_i3.ExpectedParticipantData?>{},
          )
          as Set<_i3.ExpectedParticipantData?>);

  @override
  bool get isRunning =>
      (super.noSuchMethod(Invocation.getter(#isRunning), returnValue: false, returnValueForMissingStub: false) as bool);

  @override
  Iterable<_i4.ConnectionViewModel> get deploymentDevices =>
      (super.noSuchMethod(
            Invocation.getter(#deploymentDevices),
            returnValue: <_i4.ConnectionViewModel>[],
            returnValueForMissingStub: <_i4.ConnectionViewModel>[],
          )
          as Iterable<_i4.ConnectionViewModel>);

  @override
  set study(_i2.SmartphoneStudy? study) =>
      super.noSuchMethod(Invocation.setter(#study, study), returnValueForMissingStub: null);

  @override
  _i5.Future<_i3.StudyDeploymentStatus?> refreshDeploymentStatus() =>
      (super.noSuchMethod(
            Invocation.method(#refreshDeploymentStatus, []),
            returnValue: _i5.Future<_i3.StudyDeploymentStatus?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.StudyDeploymentStatus?>.value(),
          )
          as _i5.Future<_i3.StudyDeploymentStatus?>);

  @override
  _i5.Future<void> configure() =>
      (super.noSuchMethod(
            Invocation.method(#configure, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.StudyStatus?> addStudy(_i2.SmartphoneStudy? study) =>
      (super.noSuchMethod(
            Invocation.method(#addStudy, [study]),
            returnValue: _i5.Future<_i3.StudyStatus?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.StudyStatus?>.value(),
          )
          as _i5.Future<_i3.StudyStatus?>);

  @override
  _i5.Future<_i3.StudyStatus?> tryDeployment() =>
      (super.noSuchMethod(
            Invocation.method(#tryDeployment, []),
            returnValue: _i5.Future<_i3.StudyStatus?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.StudyStatus?>.value(),
          )
          as _i5.Future<_i3.StudyStatus?>);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addMeasurement(_i3.Measurement? measurement) =>
      super.noSuchMethod(Invocation.method(#addMeasurement, [measurement]), returnValueForMissingStub: null);

  @override
  bool hasMeasures() =>
      (super.noSuchMethod(Invocation.method(#hasMeasures, []), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  bool hasMeasure(String? type) =>
      (super.noSuchMethod(Invocation.method(#hasMeasure, [type]), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  bool hasUserTasks() =>
      (super.noSuchMethod(Invocation.method(#hasUserTasks, []), returnValue: false, returnValueForMissingStub: false)
          as bool);

  @override
  void translateProtocol([_i6.RPLocalizations? localization]) =>
      super.noSuchMethod(Invocation.method(#translateProtocol, [localization]), returnValueForMissingStub: null);

  @override
  _i5.Future<List<_i3.ParticipantData>> getParticipantDataListFromDeployment() =>
      (super.noSuchMethod(
            Invocation.method(#getParticipantDataListFromDeployment, []),
            returnValue: _i5.Future<List<_i3.ParticipantData>>.value(<_i3.ParticipantData>[]),
            returnValueForMissingStub: _i5.Future<List<_i3.ParticipantData>>.value(<_i3.ParticipantData>[]),
          )
          as _i5.Future<List<_i3.ParticipantData>>);

  @override
  void setParticipantData(Map<String, _i3.Data>? data) =>
      super.noSuchMethod(Invocation.method(#setParticipantData, [data]), returnValueForMissingStub: null);

  @override
  _i5.Future<void> remove() =>
      (super.noSuchMethod(
            Invocation.method(#remove, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
