# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

  desc "Submit a new release build to Google Play's Production track"
  lane :release do
    # Auto-increment: one above the highest code on either track. This mirrors
    # the iOS Xcode Cloud CI_BUILD_NUMBER flow, so the build number never needs
    # a manual bump in pubspec.yaml.
    codes = google_play_track_version_codes(track: 'production') +
            google_play_track_version_codes(track: 'internal')
    build_number = (codes.map(&:to_i).max || 0) + 1
    build_name = YAML.load_file('../../pubspec.yaml')['version'].split('+').first
    UI.message("Building production versionCode #{build_number} (#{build_name})")

    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons --build-name=#{build_name} --build-number=#{build_number}"

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Upload to internal testing track"
  lane :test do
    # Auto-increment from the live Play state (see :release for rationale).
    codes = google_play_track_version_codes(track: 'production') +
            google_play_track_version_codes(track: 'internal')
    build_number = (codes.map(&:to_i).max || 0) + 1
    base_version = YAML.load_file('../../pubspec.yaml')['version'].split('+').first
    build_name = "#{base_version}-test"
    UI.message("Building internal versionCode #{build_number} (#{build_name})")

    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build appbundle --release --no-deferred-components --no-tree-shake-icons --dart-define='deployment-mode=test' --build-name=#{build_name} --build-number=#{build_number}"

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
